version: '3.8'

services:
  # 1. Cơ sở dữ liệu SQL Server
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Greenwich@123
    ports:
      - "1433:1433"

  # 2. Bộ nhớ đệm Redis
  redis-cache:
    image: redis:alpine
    ports:
      - "6380:6379"

  # 3. Backend API (.NET)
  backend-api:
    build: 
      context: .
      dockerfile: UrlShortener.API/Dockerfile
    ports:
      - "5078:8080" # Ánh xạ cổng ra ngoài
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Ghi đè chuỗi kết nối để trỏ vào thằng sql-db và redis-cache ở trên
      - ConnectionStrings__DefaultConnection=Server=sql-db;Database=UrlShortenerDb;User Id=sa;Password=Greenwich@123;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis-cache:6379
    depends_on:
      - sql-db
      - redis-cache

  # 4. Frontend Web (Vue.js)
  frontend-web:
    build: 
      context: ./url-shortener-web
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Bạn của bạn sẽ truy cập qua cổng này
    depends_on:
      - backend-api