version: '3.8'

services:
  # 1. SQL Server database
  sql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Greenwich@123
    ports:
      - "1433:1433"

  # 2. Redis Cache
  redis-cache:
    image: redis:alpine
    ports:
      - "6380:6379"

  # 3. Backend API (.NET)
  backend-api:
    build: 
      context: .
      dockerfile: UrlShortener.API/Dockerfile
    ports:
      - "5078:8080" # Outbound gate mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Override the connection string to point to the sql-db and redis-cache above.
      - ConnectionStrings__DefaultConnection=Server=sql-db;Database=UrlShortenerDb;User Id=sa;Password=Greenwich@123;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis-cache:6379
    depends_on:
      - sql-db
      - redis-cache

 